### ISSUE TITLE
Doesn't work when there is Groovy

### ISSUE THREAD

**Issue by boris-petrov** [nebula-plugins/gradle-jakartaee-migration-plugin#2]
[Here](https://github.com/boris-petrov/gradle-jakartaee-migration-plugin-bug) is a reproduction repo. Just run `./gradlew build` on that. It leads to:

```
> Task :compileJava NO-SOURCE
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not find org.codehaus.groovy:groovy:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy/3.0.14-jakartaee/groovy-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-ant:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-ant/3.0.14-jakartaee/groovy-ant-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-astbuilder:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-astbuilder/3.0.14-jakartaee/groovy-astbuilder-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-console:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-console/3.0.14-jakartaee/groovy-console-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-datetime:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-datetime/3.0.14-jakartaee/groovy-datetime-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-dateutil:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-dateutil/3.0.14-jakartaee/groovy-dateutil-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-nio:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-nio/3.0.14-jakartaee/groovy-nio-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-sql:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-sql/3.0.14-jakartaee/groovy-sql-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-test:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-test/3.0.14-jakartaee/groovy-test-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-templates:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-templates/3.0.14-jakartaee/groovy-templates-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-json:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-json/3.0.14-jakartaee/groovy-json-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-xml:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-xml/3.0.14-jakartaee/groovy-xml-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
   > Could not find org.codehaus.groovy:groovy-groovydoc:3.0.14-jakartaee.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-groovydoc/3.0.14-jakartaee/groovy-groovydoc-3.0.14-jakartaee.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :
```

**Comment by DanielThomas** [comment]
Thanks for the reproducer! We ran into this internally just today. Looking into it now.

```
Watching 1 directory hierarchies to track changes
Transforming groovy-astbuilder-3.0.14.jar (org.codehaus.groovy:groovy-astbuilder:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-ant-3.0.14.jar (org.codehaus.groovy:groovy-ant:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-cli-picocli-3.0.14.jar (org.codehaus.groovy:groovy-cli-picocli:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-console-3.0.14.jar (org.codehaus.groovy:groovy-console:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-datetime-3.0.14.jar (org.codehaus.groovy:groovy-datetime:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-jsr223-3.0.14.jar (org.codehaus.groovy:groovy-jsr223:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-json-3.0.14.jar (org.codehaus.groovy:groovy-json:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-groovydoc-3.0.14.jar (org.codehaus.groovy:groovy-groovydoc:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-jmx-3.0.14.jar (org.codehaus.groovy:groovy-jmx:3.0.14) with JakartaEeMigrationTransform
Transforming javaparser-core-3.24.2.jar (com.github.javaparser:javaparser-core:3.24.2) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-console/3.0.14/f5485d0958e7c7cb6e31b97810bb79d9932a1770/groovy-console-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jmx/3.0.14/d816a0167d7e3bb62d236dac68090eb27a7b5eb1/groovy-jmx-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-ant/3.0.14/d82de24d0bcc055b68e38d2f13f1c21c3bd99713/groovy-ant-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-cli-picocli/3.0.14/f0d36f20eee49fcef3413672e6d1318d8b865705/groovy-cli-picocli-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovydoc/3.0.14/6b6992090ab128ce04747c9824ac421660aa6b6a/groovy-groovydoc-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-astbuilder/3.0.14/796a55bd485fc2fd7c547ff09169f9aafd454771/groovy-astbuilder-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jsr223/3.0.14/42952a52f92bc0267a56cb91dbb342344fa21afc/groovy-jsr223-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-datetime/3.0.14/697e49171ccb1e0a5e1ac4b4c3da110093507e1d/groovy-datetime-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-json/3.0.14/2a277028ba4776c0697e2524f49d1b34d0b7668f/groovy-json-3.0.14.jar because:
  Build cache is disabled
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/com.github.javaparser/javaparser-core/3.24.2/3ace42470c37f88f78edc7ca23bc45b76d381741/javaparser-core-3.24.2.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-ant/3.0.14/d82de24d0bcc055b68e38d2f13f1c21c3bd99713/groovy-ant-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/e1f475ef2d2c8c137df7b109073c5b98/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/e1f475ef2d2c8c137df7b109073c5b98/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-astbuilder/3.0.14/796a55bd485fc2fd7c547ff09169f9aafd454771/groovy-astbuilder-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/09bb1526ddcf33e6cee469b55bb910a1/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/09bb1526ddcf33e6cee469b55bb910a1/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-datetime/3.0.14/697e49171ccb1e0a5e1ac4b4c3da110093507e1d/groovy-datetime-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/ec2a46e8270279913da1845598680e1c/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/ec2a46e8270279913da1845598680e1c/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-console/3.0.14/f5485d0958e7c7cb6e31b97810bb79d9932a1770/groovy-console-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/0115b6cbca9ce47387cc2c50e5c38176/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/0115b6cbca9ce47387cc2c50e5c38176/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jsr223/3.0.14/42952a52f92bc0267a56cb91dbb342344fa21afc/groovy-jsr223-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/b49077a59d15e97b1bd5fd502362b004/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/b49077a59d15e97b1bd5fd502362b004/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-json/3.0.14/2a277028ba4776c0697e2524f49d1b34d0b7668f/groovy-json-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/6338324cf413a35666886a90068fdb95/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/6338324cf413a35666886a90068fdb95/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/com.github.javaparser/javaparser-core/3.24.2/3ace42470c37f88f78edc7ca23bc45b76d381741/javaparser-core-3.24.2.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/0c019b4608e534cbd79644ef32b871ac/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/0c019b4608e534cbd79644ef32b871ac/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-cli-picocli/3.0.14/f0d36f20eee49fcef3413672e6d1318d8b865705/groovy-cli-picocli-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/199503ffe2271f93245f695b71a1f5d7/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/199503ffe2271f93245f695b71a1f5d7/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jmx/3.0.14/d816a0167d7e3bb62d236dac68090eb27a7b5eb1/groovy-jmx-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/3722c8097c62182afb2b123bb5e21c7e/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/3722c8097c62182afb2b123bb5e21c7e/results.bin has been removed.
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovydoc/3.0.14/6b6992090ab128ce04747c9824ac421660aa6b6a/groovy-groovydoc-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/29c567753dfce840a5bc4417b6c8ac19/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/29c567753dfce840a5bc4417b6c8ac19/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jsr223/3.0.14/42952a52f92bc0267a56cb91dbb342344fa21afc/groovy-jsr223-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee16061689971225691589transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-ant/3.0.14/d82de24d0bcc055b68e38d2f13f1c21c3bd99713/groovy-ant-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee16858111724543767534transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-jmx/3.0.14/d816a0167d7e3bb62d236dac68090eb27a7b5eb1/groovy-jmx-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee2500520584155132502transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-console/3.0.14/f5485d0958e7c7cb6e31b97810bb79d9932a1770/groovy-console-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee8882550786541451640transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-cli-picocli/3.0.14/f0d36f20eee49fcef3413672e6d1318d8b865705/groovy-cli-picocli-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee1817364528257805004transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-astbuilder/3.0.14/796a55bd485fc2fd7c547ff09169f9aafd454771/groovy-astbuilder-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee1974007492952832704transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-datetime/3.0.14/697e49171ccb1e0a5e1ac4b4c3da110093507e1d/groovy-datetime-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee2426114141541591586transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/com.github.javaparser/javaparser-core/3.24.2/3ace42470c37f88f78edc7ca23bc45b76d381741/javaparser-core-3.24.2.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee17434400114541562571transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-json/3.0.14/2a277028ba4776c0697e2524f49d1b34d0b7668f/groovy-json-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee17295427225054478850transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovydoc/3.0.14/6b6992090ab128ce04747c9824ac421660aa6b6a/groovy-groovydoc-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee2420575038664838141transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-astbuilder-3.0.14.jar] using streaming
Migration starting for archive [groovy-cli-picocli-3.0.14.jar] using streaming
Migration starting for archive [groovy-json-3.0.14.jar] using streaming
Migration starting for archive [javaparser-core-3.24.2.jar] using streaming
Migration starting for archive [groovy-ant-3.0.14.jar] using streaming
Migration starting for archive [groovy-console-3.0.14.jar] using streaming
Migration starting for archive [groovy-groovydoc-3.0.14.jar] using streaming
Migration starting for archive [groovy-jsr223-3.0.14.jar] using streaming
Migration starting for archive [groovy-jmx-3.0.14.jar] using streaming
Migration starting for archive [groovy-datetime-3.0.14.jar] using streaming
Migration finished for archive [groovy-astbuilder-3.0.14.jar]
Migration completed successfully in [56] milliseconds
No JakartaEE transformation required for groovy-astbuilder-3.0.14.jar
Migration finished for archive [groovy-jsr223-3.0.14.jar]
Migration completed successfully in [59] milliseconds
No JakartaEE transformation required for groovy-jsr223-3.0.14.jar
Migration finished for archive [groovy-datetime-3.0.14.jar]
Migration completed successfully in [61] milliseconds
No JakartaEE transformation required for groovy-datetime-3.0.14.jar
Migration finished for archive [groovy-cli-picocli-3.0.14.jar]
Migration completed successfully in [73] milliseconds
No JakartaEE transformation required for groovy-cli-picocli-3.0.14.jar
Migration finished for archive [groovy-ant-3.0.14.jar]
Migration completed successfully in [88] milliseconds
No JakartaEE transformation required for groovy-ant-3.0.14.jar
Migration finished for archive [groovy-jmx-3.0.14.jar]
Migration completed successfully in [89] milliseconds
No JakartaEE transformation required for groovy-jmx-3.0.14.jar
Transforming hamcrest-core-1.3.jar (org.hamcrest:hamcrest-core:1.3) with JakartaEeMigrationTransform
Transforming junit-4.13.2.jar (junit:junit:4.13.2) with JakartaEeMigrationTransform
Transforming opentest4j-1.2.0.jar (org.opentest4j:opentest4j:1.2.0) with JakartaEeMigrationTransform
Transforming junit-jupiter-api-5.9.1.jar (org.junit.jupiter:junit-jupiter-api:5.9.1) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/49c2ebfd8065468a031b9c4633f3f39d/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/49c2ebfd8065468a031b9c4633f3f39d/results.bin has been removed.
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/junit/junit/4.13.2/8ac9e16d933b6fb43bc7f576336b8f4d7eb5ba12/junit-4.13.2.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/junit/junit/4.13.2/8ac9e16d933b6fb43bc7f576336b8f4d7eb5ba12/junit-4.13.2.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/2abf9539b80714ba4e0b50f359b1550b/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/2abf9539b80714ba4e0b50f359b1550b/results.bin has been removed.
Transforming groovy-sql-3.0.14.jar (org.codehaus.groovy:groovy-sql:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.9.1/7bb53fbc0173e9f6a9d21d58297af94b1f2f9ce1/junit-jupiter-api-5.9.1.jar because:
  Build cache is disabled
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee4124473319882764164transform] with Jakarta EE specification profile [EE]
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.9.1/7bb53fbc0173e9f6a9d21d58297af94b1f2f9ce1/junit-jupiter-api-5.9.1.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/46a28c08b733c00d7da5c7d57f5b8aee/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/46a28c08b733c00d7da5c7d57f5b8aee/results.bin has been removed.
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.2.0/28c11eb91f9b6d8e200631d46e20a7f407f2a046/opentest4j-1.2.0.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.2.0/28c11eb91f9b6d8e200631d46e20a7f407f2a046/opentest4j-1.2.0.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/aba480592f7c60df433dc4b011a7d74d/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/aba480592f7c60df433dc4b011a7d74d/results.bin has been removed.
Migration starting for archive [hamcrest-core-1.3.jar] using streaming
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/junit/junit/4.13.2/8ac9e16d933b6fb43bc7f576336b8f4d7eb5ba12/junit-4.13.2.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee12264714365274135434transform] with Jakarta EE specification profile [EE]
Migration starting for archive [junit-4.13.2.jar] using streaming
Transforming groovy-nio-3.0.14.jar (org.codehaus.groovy:groovy-nio:3.0.14) with JakartaEeMigrationTransform
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.9.1/7bb53fbc0173e9f6a9d21d58297af94b1f2f9ce1/junit-jupiter-api-5.9.1.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee637661585033919328transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.2.0/28c11eb91f9b6d8e200631d46e20a7f407f2a046/opentest4j-1.2.0.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee9053787034176079545transform] with Jakarta EE specification profile [EE]
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-sql/3.0.14/e729da5ec56f61342c6df26b84f1e74ea1acf695/groovy-sql-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-sql/3.0.14/e729da5ec56f61342c6df26b84f1e74ea1acf695/groovy-sql-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/58245b0adbc7b8b0a1a7b59c097f6dbc/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/58245b0adbc7b8b0a1a7b59c097f6dbc/results.bin has been removed.
Migration starting for archive [opentest4j-1.2.0.jar] using streaming
Migration starting for archive [junit-jupiter-api-5.9.1.jar] using streaming
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-nio/3.0.14/a0e5387e6683b7d66d9ba458858c4b73111b4948/groovy-nio-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-nio/3.0.14/a0e5387e6683b7d66d9ba458858c4b73111b4948/groovy-nio-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/b5fe56efdf5f305e5ed05f36bae48f2e/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/b5fe56efdf5f305e5ed05f36bae48f2e/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-sql/3.0.14/e729da5ec56f61342c6df26b84f1e74ea1acf695/groovy-sql-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee3494822435045339616transform] with Jakarta EE specification profile [EE]
Migration finished for archive [groovy-groovydoc-3.0.14.jar]
Migration starting for archive [groovy-sql-3.0.14.jar] using streaming
Migration completed successfully in [100] milliseconds
No JakartaEE transformation required for groovy-groovydoc-3.0.14.jar
Migration finished for archive [opentest4j-1.2.0.jar]
Migration completed successfully in [4] milliseconds
No JakartaEE transformation required for opentest4j-1.2.0.jar
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-nio/3.0.14/a0e5387e6683b7d66d9ba458858c4b73111b4948/groovy-nio-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee10948545572728892522transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-nio-3.0.14.jar] using streaming
Transforming ant-1.10.12.jar (org.apache.ant:ant:1.10.12) with JakartaEeMigrationTransform
Migration finished for archive [groovy-nio-3.0.14.jar]
Migration completed successfully in [9] milliseconds
No JakartaEE transformation required for groovy-nio-3.0.14.jar
Transforming groovy-testng-3.0.14.jar (org.codehaus.groovy:groovy-testng:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.10.12/be08c4f63e92e03bac761404cf77bc270928b6c5/ant-1.10.12.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.10.12/be08c4f63e92e03bac761404cf77bc270928b6c5/ant-1.10.12.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/8929300619a60cbff5a267914721a0af/transformed has been removed.
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/8929300619a60cbff5a267914721a0af/transformed/ant-1.10.12-jakartaee.jar has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/8929300619a60cbff5a267914721a0af/results.bin has been removed.
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-testng/3.0.14/84f5a8759fa237a8c86b747d92d561e43847c9cb/groovy-testng-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-testng/3.0.14/84f5a8759fa237a8c86b747d92d561e43847c9cb/groovy-testng-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/2dd7e92d060d8f7a18ae8ac517a43f9d/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/2dd7e92d060d8f7a18ae8ac517a43f9d/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-testng/3.0.14/84f5a8759fa237a8c86b747d92d561e43847c9cb/groovy-testng-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee3916802737370945487transform] with Jakarta EE specification profile [EE]
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.10.12/be08c4f63e92e03bac761404cf77bc270928b6c5/ant-1.10.12.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee16273394252344430710transform] with Jakarta EE specification profile [EE]
Migration finished for archive [hamcrest-core-1.3.jar]
Migration completed successfully in [24] milliseconds
No JakartaEE transformation required for hamcrest-core-1.3.jar
Migration starting for archive [ant-1.10.12.jar] using streaming
Migration starting for archive [groovy-testng-3.0.14.jar] using streaming
Migration finished for archive [groovy-testng-3.0.14.jar]
Migration completed successfully in [4] milliseconds
No JakartaEE transformation required for groovy-testng-3.0.14.jar
Transforming groovy-servlet-3.0.14.jar (org.codehaus.groovy:groovy-servlet:3.0.14) with JakartaEeMigrationTransform
Transforming groovy-xml-3.0.14.jar (org.codehaus.groovy:groovy-xml:3.0.14) with JakartaEeMigrationTransform
Migration finished for archive [groovy-sql-3.0.14.jar]
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-servlet/3.0.14/6841889d1dff7325a238b7847099a159efb4adc2/groovy-servlet-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-servlet/3.0.14/6841889d1dff7325a238b7847099a159efb4adc2/groovy-servlet-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/8b8b37a721c8d3f1a53e0ea15978c8ae/transformed has been removed.
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/8b8b37a721c8d3f1a53e0ea15978c8ae/transformed/groovy-servlet-3.0.14-jakartaee.jar has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/8b8b37a721c8d3f1a53e0ea15978c8ae/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-servlet/3.0.14/6841889d1dff7325a238b7847099a159efb4adc2/groovy-servlet-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee12412850098969613126transform] with Jakarta EE specification profile [EE]
Transforming groovy-test-3.0.14.jar (org.codehaus.groovy:groovy-test:3.0.14) with JakartaEeMigrationTransform
Migration completed successfully in [36] milliseconds
No JakartaEE transformation required for groovy-sql-3.0.14.jar
Migration starting for archive [groovy-servlet-3.0.14.jar] using streaming
Migration finished for archive [groovy-json-3.0.14.jar]
Migration completed successfully in [138] milliseconds
No JakartaEE transformation required for groovy-json-3.0.14.jar
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-xml/3.0.14/1f23ec36710c6938768065801ac3bd12178b8ba4/groovy-xml-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-xml/3.0.14/1f23ec36710c6938768065801ac3bd12178b8ba4/groovy-xml-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/3b3eca25cb6eb9231eaa74d6a84045b9/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/3b3eca25cb6eb9231eaa74d6a84045b9/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-xml/3.0.14/1f23ec36710c6938768065801ac3bd12178b8ba4/groovy-xml-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee18221550831951479898transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-xml-3.0.14.jar] using streaming
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test/3.0.14/21973950a1b13d92a0cdbaa30b49d6bb44b028d/groovy-test-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test/3.0.14/21973950a1b13d92a0cdbaa30b49d6bb44b028d/groovy-test-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/f915b503b2c5ee3936b3f9d2fbe1cd65/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/f915b503b2c5ee3936b3f9d2fbe1cd65/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test/3.0.14/21973950a1b13d92a0cdbaa30b49d6bb44b028d/groovy-test-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee6811800766470783143transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-test-3.0.14.jar] using streaming
Migration finished for archive [groovy-servlet-3.0.14.jar]
Migration completed successfully in [15] milliseconds
Transforming groovy-swing-3.0.14.jar (org.codehaus.groovy:groovy-swing:3.0.14) with JakartaEeMigrationTransform
Transformed groovy-servlet-3.0.14.jar to JakartaEE groovy-servlet-3.0.14-jakartaee.jar
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-swing/3.0.14/dbe0e69c1ed45de284c4595f4f6e612d78ccfb4c/groovy-swing-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-swing/3.0.14/dbe0e69c1ed45de284c4595f4f6e612d78ccfb4c/groovy-swing-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/4a4810f7de9c091d5c9ce56e508f671f/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/4a4810f7de9c091d5c9ce56e508f671f/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-swing/3.0.14/dbe0e69c1ed45de284c4595f4f6e612d78ccfb4c/groovy-swing-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee9358199415020844404transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-swing-3.0.14.jar] using streaming
Transforming groovy-macro-3.0.14.jar (org.codehaus.groovy:groovy-macro:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-macro/3.0.14/d4963a1b0f78f4650f89c83c53be54b1ae13f07e/groovy-macro-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-macro/3.0.14/d4963a1b0f78f4650f89c83c53be54b1ae13f07e/groovy-macro-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/f01fa07052e7cd39a57af5012d27de4e/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/f01fa07052e7cd39a57af5012d27de4e/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-macro/3.0.14/d4963a1b0f78f4650f89c83c53be54b1ae13f07e/groovy-macro-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee6131509182243448103transform] with Jakarta EE specification profile [EE]
Migration finished for archive [groovy-test-3.0.14.jar]
Migration completed successfully in [33] milliseconds
No JakartaEE transformation required for groovy-test-3.0.14.jar
Migration starting for archive [groovy-macro-3.0.14.jar] using streaming
Transforming groovy-3.0.14.jar (org.codehaus.groovy:groovy:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.14/972cd630f59b9eeb28f4fea5872f9fa4f92c4535/groovy-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.14/972cd630f59b9eeb28f4fea5872f9fa4f92c4535/groovy-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/3f46f35409027e7b7fd16c97f0b84180/transformed has been removed.
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/3f46f35409027e7b7fd16c97f0b84180/transformed/groovy-3.0.14-jakartaee.jar has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/3f46f35409027e7b7fd16c97f0b84180/results.bin has been removed.
Migration finished for archive [junit-jupiter-api-5.9.1.jar]
Migration completed successfully in [114] milliseconds
No JakartaEE transformation required for junit-jupiter-api-5.9.1.jar
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.14/972cd630f59b9eeb28f4fea5872f9fa4f92c4535/groovy-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee7447831570609286972transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-3.0.14.jar] using streaming
Transforming groovy-groovysh-3.0.14.jar (org.codehaus.groovy:groovy-groovysh:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovysh/3.0.14/743d02ffd6ecb21ac985e8ca238799bf3926752b/groovy-groovysh-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovysh/3.0.14/743d02ffd6ecb21ac985e8ca238799bf3926752b/groovy-groovysh-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/b375c1fa76e9b362a512d215076a4015/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/b375c1fa76e9b362a512d215076a4015/results.bin has been removed.
Transforming groovy-templates-3.0.14.jar (org.codehaus.groovy:groovy-templates:3.0.14) with JakartaEeMigrationTransform
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-groovysh/3.0.14/743d02ffd6ecb21ac985e8ca238799bf3926752b/groovy-groovysh-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee9491614065595534943transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-groovysh-3.0.14.jar] using streaming
Migration finished for archive [groovy-xml-3.0.14.jar]
Migration completed successfully in [105] milliseconds
No JakartaEE transformation required for groovy-xml-3.0.14.jar
Migration finished for archive [groovy-macro-3.0.14.jar]
Migration completed successfully in [84] milliseconds
No JakartaEE transformation required for groovy-macro-3.0.14.jar
Transforming groovy-docgenerator-3.0.14.jar (org.codehaus.groovy:groovy-docgenerator:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-docgenerator/3.0.14/5a40fa1e62d3707372d8b43f1f2327323e1db60/groovy-docgenerator-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-docgenerator/3.0.14/5a40fa1e62d3707372d8b43f1f2327323e1db60/groovy-docgenerator-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/a27aa51c7496a13fafc1610bf7d1dfec/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/a27aa51c7496a13fafc1610bf7d1dfec/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-docgenerator/3.0.14/5a40fa1e62d3707372d8b43f1f2327323e1db60/groovy-docgenerator-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee3474482829658719192transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-docgenerator-3.0.14.jar] using streaming
Migration finished for archive [junit-4.13.2.jar]
Migration completed successfully in [186] milliseconds
No JakartaEE transformation required for junit-4.13.2.jar
Transforming groovy-test-junit5-3.0.14.jar (org.codehaus.groovy:groovy-test-junit5:3.0.14) with JakartaEeMigrationTransform
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test-junit5/3.0.14/e4364a6275a5637419785a8a58e13f03a572968b/groovy-test-junit5-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test-junit5/3.0.14/e4364a6275a5637419785a8a58e13f03a572968b/groovy-test-junit5-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/95b594f378a2ae854e412c1d046039a7/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/95b594f378a2ae854e412c1d046039a7/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-test-junit5/3.0.14/e4364a6275a5637419785a8a58e13f03a572968b/groovy-test-junit5-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee13723976441411087174transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-test-junit5-3.0.14.jar] using streaming
Migration finished for archive [groovy-test-junit5-3.0.14.jar]
Migration completed successfully in [3] milliseconds
No JakartaEE transformation required for groovy-test-junit5-3.0.14.jar
Migration finished for archive [groovy-docgenerator-3.0.14.jar]
Migration completed successfully in [31] milliseconds
No JakartaEE transformation required for groovy-docgenerator-3.0.14.jar
Migration finished for archive [groovy-swing-3.0.14.jar]
Migration completed successfully in [134] milliseconds
No JakartaEE transformation required for groovy-swing-3.0.14.jar
Migration finished for archive [groovy-groovysh-3.0.14.jar]
Migration completed successfully in [174] milliseconds
No JakartaEE transformation required for groovy-groovysh-3.0.14.jar
Migration finished for archive [javaparser-core-3.24.2.jar]
Migration completed successfully in [435] milliseconds
No JakartaEE transformation required for javaparser-core-3.24.2.jar
Migration finished for archive [groovy-console-3.0.14.jar]
Migration completed successfully in [458] milliseconds
No JakartaEE transformation required for groovy-console-3.0.14.jar
Migration finished for archive [ant-1.10.12.jar]
Migration completed successfully in [438] milliseconds
Transformed ant-1.10.12.jar to JakartaEE ant-1.10.12-jakartaee.jar
Caching disabled for JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-templates/3.0.14/9c9c5afe1a29f8e4097c0f51e186698d88fda6b2/groovy-templates-3.0.14.jar because:
  Build cache is disabled
JakartaEeMigrationTransform: /Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-templates/3.0.14/9c9c5afe1a29f8e4097c0f51e186698d88fda6b2/groovy-templates-3.0.14.jar is not up-to-date because:
  Output property 'outputDirectory' file /Users/dannyt/.gradle/caches/transforms-3/0d8b5029c85f065bd1967791a0cec03b/transformed has been removed.
  Output property 'resultsFile' file /Users/dannyt/.gradle/caches/transforms-3/0d8b5029c85f065bd1967791a0cec03b/results.bin has been removed.
Performing migration from source [/Users/dannyt/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-templates/3.0.14/9c9c5afe1a29f8e4097c0f51e186698d88fda6b2/groovy-templates-3.0.14.jar] to destination [/var/folders/gl/9qw1jzv11r5_vxh0ngrk1hcw0000gn/T/jakartaee8749230493680201544transform] with Jakarta EE specification profile [EE]
Migration starting for archive [groovy-templates-3.0.14.jar] using streaming
Migration finished for archive [groovy-templates-3.0.14.jar]
Migration completed successfully in [12] milliseconds
No JakartaEE transformation required for groovy-templates-3.0.14.jar
Migration finished for archive [groovy-3.0.14.jar]
Migration completed successfully in [1,069] milliseconds
Transformed groovy-3.0.14.jar to JakartaEE groovy-3.0.14-jakartaee.jar
```

**Comment by DanielThomas** [comment]
This is caused by the way Gradle infers the Groovy version to build the runtime classpath for Groovy:

- https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/tasks/GroovyRuntime.java#L148-L162
- https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/GroovyJarFile.java#L47

I'd be better if they used the jar manifest, rather than coupling to the artifact filename, could you report this upstream please?

The migrator is hitting a class that shouldn't be migrated anyway. I'll think about adding some default excludes:
```
Migrated class [org.codehaus.groovy.vmplugin.v9.Java9.class]
No conversion necessary for [META-INF/INDEX.LIST]
Migration finished for archive [groovy-3.0.14.jar]
Migration completed successfully in [1,317] milliseconds
```

What we're doing internally currently is:
```
      // Intentional references to legacy javax package names
      excludeTransform('org.springframework:spring-context')
      excludeTransform('org.springframework:spring-beans')
      excludeTransform('org.apache.tomcat.embed:tomcat-embed-core')
      excludeTransform('org.apache.groovy:groovy')
```

**Comment by iuliiasobolevska** [comment]
I've been actually hitting this issue with our internal `excludeTransform`s being present in SBN. 

Workaround that worked for me was to upgrade to `org.apache.groovy:groovy:4.+` and exclude older `org.codehaus.groovy:groovy` versions.

**Comment by DanielThomas** [comment]
@iuliiasobolevska yep, that's why I was looking at this. Fixed by https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin/releases/tag/v0.4.0

**Comment by boris-petrov** [comment]
@DanielThomas thanks for the release! However, I still can't get it to work - my reproduction repo also fails even with version 0.4.0. Using Groovy 4 as @iuliiasobolevska su suggested fixes the issue though.

**Comment by DanielThomas** [comment]
@boris-petrov oh right, `all` and `indy` totally slipped my mind. I'll get those added tomorrow.

**Comment by DanielThomas** [comment]
Out with 0.5.0.
